// Run: node scripts/populate_tags.mjs
// Populates tags on all resources using Supabase client with admin auth

import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://aszhjzseobgadbgxaosq.supabase.co',
  'sb_publishable_Pak6sxTym3hMbH9f0_qy9Q_JKFW0-1L'
);

// Tag mapping: resource name -> tags array
const tagMap = {
  // Companies / Newsletters
  '4sight Health': ['newsletter', 'strategy', 'healthcare'],
  'American Hospital Association': ['association', 'hospital', 'policy'],
  'AJHCS (American Journal of Healthcare Strategy)': ['journal', 'strategy', 'C-suite'],
  "Becker's Healthcare": ['newsletter', 'news', 'C-suite'],
  'BioPharmaDrive': ['news', 'pharmacy', 'newsletter'],
  'Business of Primary Care': ['newsletter', 'physician', 'ambulatory'],
  'Chief Healthcare Executive': ['news', 'C-suite', 'leadership'],
  'Digital Healthwire': ['newsletter', 'digital health', 'technology'],
  'Drug Channels Institute': ['newsletter', 'pharmacy', 'supply chain'],
  'EndPoint News': ['news', 'pharmacy', 'clinical'],
  'HealthEconomics.com': ['research', 'healthcare', 'policy'],
  'HIRC (Healthcare Industry Resilience Collaborative)': ['association', 'supply chain', 'healthcare'],
  'Fierce Healthcare': ['news', 'healthcare', 'newsletter'],
  'Fierce Pharma': ['news', 'pharmacy', 'newsletter'],
  'Gist Health': ['newsletter', 'healthcare', 'strategy'],
  'Harvard Business Review': ['journal', 'leadership', 'strategy'],
  'Healthcare Executive': ['magazine', 'C-suite', 'leadership'],
  'HealthLeaders': ['news', 'C-suite', 'leadership'],
  'Healthcare Dive': ['news', 'healthcare', 'newsletter'],
  'Healthcare Innovation': ['news', 'technology', 'innovation'],
  'Health Management Academy': ['research', 'C-suite', 'health system'],
  'Healthcare Purchasing News': ['news', 'supply chain', 'hospital'],
  'Healthcare Tech Outlook': ['news', 'technology', 'healthcare'],
  'Healthcare Transformers': ['newsletter', 'innovation', 'healthcare'],
  'Healthcare Value Analysis & Utilization Management Magazine': ['magazine', 'supply chain', 'hospital'],
  'Hospitalogy': ['newsletter', 'health system', 'strategy'],
  'Journal of Healthcare Contracting': ['magazine', 'supply chain', 'healthcare'],
  'Kaiser Health News': ['news', 'healthcare', 'policy'],
  'Kaufman Hall Flash Report': ['research', 'CFO', 'hospital'],
  'MarketScale': ['news', 'healthcare', 'technology'],
  'MassDevice': ['news', 'technology', 'healthcare'],
  'McKinsey & Company': ['consulting', 'strategy', 'health system'],
  'MedCity News': ['news', 'healthcare', 'innovation'],
  'Medical News Today': ['news', 'clinical', 'healthcare'],
  'Medical Marketing + Media': ['magazine', 'pharmacy', 'healthcare'],
  'MedTech Dive': ['news', 'technology', 'healthcare'],
  'Med Tech Outlook': ['news', 'technology', 'healthcare'],
  'Modern Healthcare': ['news', 'healthcare', 'C-suite'],
  'Orthopedic Network News (ONN)': ['newsletter', 'supply chain', 'clinical'],
  'Orthoworld': ['news', 'clinical', 'healthcare'],
  'Orthopedic Design & Technology': ['magazine', 'technology', 'clinical'],
  'OR Today': ['magazine', 'clinical', 'hospital'],
  'Out-Of-Pocket': ['newsletter', 'healthcare', 'innovation'],
  'Pharma Tech Outlook': ['news', 'pharmacy', 'technology'],
  'PharmaVoice': ['magazine', 'pharmacy', 'healthcare'],
  'QMed MD+DI': ['news', 'technology', 'healthcare'],
  'Repertoire Magazine': ['magazine', 'supply chain', 'healthcare'],
  'Revenue Cycle Resources-RCR Hub': ['newsletter', 'revenue cycle', 'healthcare'],
  'STAT': ['news', 'healthcare', 'clinical'],
  'StartUp Health': ['news', 'digital health', 'innovation'],

  // Industry Meetings
  'AACP (American Association of Colleges of Pharmacy)': ['conference', 'association', 'pharmacy'],
  'AAMI (Association for the Advancement of Medical Instrumentation)': ['conference', 'association', 'technology'],
  'AAPPR (Association for Advancing Physician and Provider Recruitment)': ['conference', 'association', 'workforce'],
  'AAOS (American Academy of Orthopedic Surgeons)': ['conference', 'association', 'clinical'],
  'ACOG (American College of Obstetricians and Gynecologists)': ['conference', 'association', 'clinical'],
  'AHIMA (American Health Information Management Association)': ['conference', 'association', 'data analytics'],
  'ACHE (American College of Healthcare Executives)': ['conference', 'association', 'C-suite'],
  'AHRMM (Association for Health Care Resources & Materials Management)': ['conference', 'association', 'supply chain'],
  'AHVAP (Association of Healthcare Value Analysis Professionals)': ['conference', 'association', 'supply chain'],
  'ANAE (Association of National Account Executives)': ['conference', 'association', 'supply chain'],
  'APIC (Association for Professionals in Infection Control and Epidemiology)': ['conference', 'association', 'clinical'],
  'ASCA (Ambulatory Surgery Center Association)': ['conference', 'association', 'ambulatory'],
  'ASCP (American Society for Clinical Pathology)': ['conference', 'association', 'clinical'],
  'ASH (American Society of Hematology)': ['conference', 'association', 'clinical'],
  'ASHHRA (American Society for Healthcare Human Resources Administration)': ['conference', 'association', 'workforce'],
  'ASHP (American Society of Health-System Pharmacists)': ['conference', 'association', 'pharmacy'],
  'AONL (American Organization for Nursing Leadership)': ['conference', 'association', 'nursing'],
  'AORN (Association of periOperative Registered Nurses)': ['conference', 'association', 'nursing'],
  'Asembia-Speciality Pharmacy Summit': ['conference', 'pharmacy', 'healthcare'],
  'ASCO (American Society of Clinical Oncology)': ['conference', 'association', 'clinical'],
  'ATA (American Telemedicine Association)': ['conference', 'association', 'telehealth'],
  'AHA Leadership Summit': ['conference', 'leadership', 'hospital'],
  'CHIME/HIMSS': ['conference', 'technology', 'CIO'],
  'Clin-Ops': ['conference', 'clinical', 'supply chain'],
  'Club CMIO': ['conference', 'technology', 'clinical'],
  'ECRI': ['conference', 'supply chain', 'safety'],
  'Federation of American Hospitals': ['conference', 'policy', 'hospital'],
  'GHX Summit': ['conference', 'supply chain', 'technology'],
  'HPN Summit': ['conference', 'supply chain', 'healthcare'],
  'HIDA Streamlining Conference': ['conference', 'supply chain', 'healthcare'],
  'Health Connect Partners': ['conference', 'supply chain', 'healthcare'],
  'Healthcare Design Expo': ['conference', 'facilities', 'healthcare'],
  'HLTH': ['conference', 'innovation', 'digital health'],
  'IDN Summit': ['conference', 'supply chain', 'C-suite'],
  'J.P. Morgan Healthcare Conference': ['conference', 'strategy', 'CFO'],
  'MGMA': ['conference', 'association', 'physician'],
  'McKesson ideaShare': ['conference', 'pharmacy', 'supply chain'],
  'Med Assets / Vizient Connections Summit': ['conference', 'GPO', 'supply chain'],
  'National Association of Chain Drug Stores': ['conference', 'pharmacy', 'association'],
  'PACK EXPO': ['conference', 'supply chain', 'technology'],
  'Scottsdale Institute': ['conference', 'technology', 'C-suite'],
  'SHSMD Connections': ['conference', 'association', 'strategy'],
  'SMI (Strategic Marketplace Initiative)': ['conference', 'supply chain', 'strategy'],
  'ViVE': ['conference', 'technology', 'innovation'],
  'Workday Rising': ['conference', 'technology', 'workforce'],

  // Industry Meetings — Pharmacy
  'AMCP (Academy of Managed Care Pharmacy)': ['conference', 'pharmacy', 'association'],
  'ASHP Midyear Clinical Meeting': ['conference', 'pharmacy', 'clinical'],
  'ASCP Annual Meeting': ['conference', 'pharmacy', 'association'],
  'CPNP (College of Psychiatric and Neurologic Pharmacists)': ['conference', 'pharmacy', 'clinical'],
  'Drug Information Association': ['conference', 'pharmacy', 'regulatory'],
  'HOPA (Hematology/Oncology Pharmacy Association)': ['conference', 'pharmacy', 'clinical'],
  'ISMP (Institute for Safe Medication Practices)': ['conference', 'pharmacy', 'safety'],
  'ISPE (International Society for Pharmaceutical Engineering)': ['conference', 'pharmacy', 'technology'],
  'Managed Markets Pharmacy Summit': ['conference', 'pharmacy', 'payer'],
  'NCPA (National Community Pharmacists Association)': ['conference', 'pharmacy', 'association'],
  'PBA Health (Pharmacy Buying Alliance)': ['conference', 'pharmacy', 'GPO'],
  'Pharmacy HIT Collaborative': ['conference', 'pharmacy', 'technology'],
  'PTCB (Pharmacy Technician Certification Board)': ['conference', 'pharmacy', 'workforce'],
  'Specialty Pharmacy Summit': ['conference', 'pharmacy', 'clinical'],
  'USP (United States Pharmacopeia)': ['conference', 'pharmacy', 'regulatory'],
  'Vizient Pharmacy Network Meeting': ['conference', 'pharmacy', 'GPO'],
  'NACDS Annual Meeting': ['conference', 'pharmacy', 'association'],
  'NCODA (National Clinical Oncology Development Alliance)': ['conference', 'pharmacy', 'clinical'],
  'NHA (National Hospice Alliance) Pharmacy Summit': ['conference', 'pharmacy', 'clinical'],
  'Omnicell Insights Forum': ['conference', 'pharmacy', 'technology'],
  'PharmaForce International': ['conference', 'pharmacy', 'supply chain'],
  'RBC Capital Markets Healthcare Conference': ['conference', 'pharmacy', 'strategy'],
  'SAHP (Society of Adventist Health-System Pharmacists)': ['conference', 'pharmacy', 'association'],
  'SGIM (Society of General Internal Medicine) Pharmacy Track': ['conference', 'pharmacy', 'clinical'],
  'SOHO (Society of Hospital Medicine) Pharmacy Symposium': ['conference', 'pharmacy', 'hospital'],
  'Therigy Client Conference': ['conference', 'pharmacy', 'technology'],
  'Vizient Pharmacy Connections Summit': ['conference', 'pharmacy', 'GPO'],
  'XRx (Crossroads of Pharmacy)': ['conference', 'pharmacy', 'innovation'],

  // Industry Meetings — Technology
  'CHIME Fall Forum': ['conference', 'technology', 'CIO'],
  'CHIME Spring Forum': ['conference', 'technology', 'CIO'],
  'HIMSS Global Health Conference': ['conference', 'technology', 'digital health'],
  'Health 2.0': ['conference', 'technology', 'innovation'],
  'Healthcare AI Summit': ['conference', 'technology', 'AI'],
  'HIT Leadership Summit': ['conference', 'technology', 'CIO'],
  'KLAS Keystone Summit': ['conference', 'technology', 'healthcare'],
  'MEDITECH LIVE': ['conference', 'technology', 'healthcare'],
  'Microsoft Healthcare Summit': ['conference', 'technology', 'AI'],
  'Oracle Health Conference': ['conference', 'technology', 'healthcare'],
  'Scottsdale Institute Fall Conference': ['conference', 'technology', 'C-suite'],
  'ServiceNow Knowledge': ['conference', 'technology', 'healthcare'],
  'Workday Healthcare Summit': ['conference', 'technology', 'workforce'],
  'Epic UGM (Users Group Meeting)': ['conference', 'technology', 'healthcare'],
  'Gartner IT Symposium': ['conference', 'technology', 'strategy'],
  'Google Health Connect': ['conference', 'technology', 'AI'],
  'AWS re:Invent Healthcare Track': ['conference', 'technology', 'AI'],

  // Industry Meetings — Revenue Cycle
  'AAHAM (American Association of Healthcare Administrative Management)': ['conference', 'revenue cycle', 'association'],
  'HFMA Annual Conference': ['conference', 'revenue cycle', 'CFO'],
  'NAHAM (National Association of Healthcare Access Management)': ['conference', 'revenue cycle', 'association'],
  'Revenue Cycle Summit': ['conference', 'revenue cycle', 'healthcare'],
  'Becker\'s Revenue Cycle Management Summit': ['conference', 'revenue cycle', 'C-suite'],
  'CAQH Annual Conference': ['conference', 'revenue cycle', 'interoperability'],
  'Change Healthcare User Conference': ['conference', 'revenue cycle', 'technology'],
  'Crowe Healthcare Revenue Cycle Forum': ['conference', 'revenue cycle', 'consulting'],
  'Waystar Client Summit': ['conference', 'revenue cycle', 'technology'],

  // Industry Meetings — Facilities
  'ASHE (American Society for Healthcare Engineering)': ['conference', 'facilities', 'association'],
  'AHE (Association for the Healthcare Environment)': ['conference', 'facilities', 'association'],
  'APPA (Association of Physical Plant Administrators)': ['conference', 'facilities', 'association'],
  'Healthcare Facilities Symposium': ['conference', 'facilities', 'healthcare'],
  'IFMA (International Facility Management Association)': ['conference', 'facilities', 'association'],
  'PDC Summit': ['conference', 'facilities', 'healthcare'],
  'AIA Academy on Architecture for Health': ['conference', 'facilities', 'healthcare'],
  'CleanMed Conference': ['conference', 'facilities', 'healthcare'],
  'Environment of Care Summit': ['conference', 'facilities', 'safety'],
  'Health Facilities Innovation Forum': ['conference', 'facilities', 'innovation'],
  'Practice Greenhealth Environmental Excellence Awards': ['conference', 'facilities', 'healthcare'],

  // Industry Meetings — Supply Chain
  'Bellwether League': ['conference', 'supply chain', 'leadership'],
  'Health Industry Distributors Association (HIDA)': ['conference', 'supply chain', 'association'],
  'HSCA (Healthcare Supply Chain Association)': ['conference', 'supply chain', 'association'],
  'Medical Device Manufacturers Association': ['conference', 'supply chain', 'association'],
  'Premier Breakthroughs Conference': ['conference', 'supply chain', 'GPO'],
  'Vizient Connections Summit': ['conference', 'supply chain', 'GPO'],
  'AdvaMed MedTech Conference': ['conference', 'supply chain', 'technology'],
  'Concordance Healthcare Solutions Summit': ['conference', 'supply chain', 'healthcare'],
  'GHX Nexus': ['conference', 'supply chain', 'technology'],
  'Health Industry Group Purchasing Association': ['conference', 'supply chain', 'GPO'],
  'Healthcare Purchasing Symposium': ['conference', 'supply chain', 'healthcare'],
  'MDSI (Medical Device & Supply Industry) Conference': ['conference', 'supply chain', 'association'],
  'Medline Supplier Summit': ['conference', 'supply chain', 'healthcare'],
  'Owens & Minor Innovation Summit': ['conference', 'supply chain', 'innovation'],
  'RepConnect': ['conference', 'supply chain', 'healthcare'],
  'Supply Chain Automation Expo': ['conference', 'supply chain', 'technology'],
  'Value Analysis Collaborative Summit': ['conference', 'supply chain', 'healthcare'],
  'W.B. Mason Healthcare Division Summit': ['conference', 'supply chain', 'healthcare'],
  'Yankee Alliance National Conference': ['conference', 'supply chain', 'GPO'],

  // GPOs
  'Vizient': ['GPO', 'supply chain', 'health system'],
  'Premier Inc.': ['GPO', 'supply chain', 'health system'],
  'HealthTrust (HCA)': ['GPO', 'supply chain', 'hospital'],
  'Intalere': ['GPO', 'supply chain', 'healthcare'],
  'ROi (Resource Optimization & Innovation)': ['GPO', 'supply chain', 'healthcare'],
  'Yankee Alliance': ['GPO', 'supply chain', 'healthcare'],
  'Capstone Health Alliance': ['GPO', 'supply chain', 'healthcare'],
  'Children\'s Hospital Association': ['GPO', 'association', 'hospital'],
  'GNYHA (Greater New York Hospital Association)': ['GPO', 'association', 'hospital'],
  'HPG (Healthcare Purchasing Group)': ['GPO', 'supply chain', 'healthcare'],
  'Managed Health Care Associates': ['GPO', 'pharmacy', 'healthcare'],
  'National Purchasing Partners': ['GPO', 'supply chain', 'healthcare'],
  'Provista': ['GPO', 'supply chain', 'healthcare'],
  'TPC (The Purchasing Connection)': ['GPO', 'supply chain', 'healthcare'],
  'US Communities': ['GPO', 'supply chain', 'healthcare'],
  'Vizient Novation': ['GPO', 'supply chain', 'healthcare'],
  'Acurity (formerly HHSC)': ['GPO', 'supply chain', 'healthcare'],

  // Federal Government / CMS
  'CMS.gov': ['government', 'policy', 'healthcare'],
  'HHS.gov': ['government', 'policy', 'healthcare'],
  'FDA.gov': ['government', 'regulatory', 'clinical'],
  'CDC.gov': ['government', 'clinical', 'policy'],
  'NIH.gov': ['government', 'research', 'clinical'],
  'VA.gov': ['government', 'hospital', 'healthcare'],
  'AHRQ (Agency for Healthcare Research and Quality)': ['government', 'research', 'quality'],
  'OIG (Office of Inspector General)': ['government', 'regulatory', 'healthcare'],
  'GAO Healthcare Reports': ['government', 'research', 'policy'],
  'MedPAC (Medicare Payment Advisory Commission)': ['government', 'policy', 'payer'],
  'MACPAC (Medicaid and CHIP Payment Advisory Commission)': ['government', 'policy', 'payer'],
  'CBO Health Analyses': ['government', 'research', 'policy'],
  'HRSA.gov': ['government', 'workforce', 'healthcare'],
  'SAMHSA.gov': ['government', 'behavioral health', 'policy'],
  'USAspending.gov': ['government', 'data analytics', 'healthcare'],

  // Resources
  'AHA Data & Insights': ['research', 'data analytics', 'hospital'],
  'AHA Guides & Reports': ['research', 'policy', 'hospital'],
  'ECRI Institute': ['research', 'safety', 'technology'],
  'The Commonwealth Fund': ['research', 'policy', 'healthcare'],
  'The Advisory Board': ['research', 'strategy', 'health system'],
  'The Leapfrog Group': ['research', 'quality', 'safety'],
  'Press Ganey': ['research', 'patient experience', 'quality'],
  'Sg2': ['research', 'strategy', 'health system'],
  'Chartis Group': ['consulting', 'strategy', 'health system'],
  'Guidehouse': ['consulting', 'strategy', 'healthcare'],
  'Huron Consulting': ['consulting', 'strategy', 'healthcare'],
  'Navigant (Guidehouse)': ['consulting', 'strategy', 'healthcare'],
  'Deloitte Health Care': ['consulting', 'strategy', 'health system'],
  'PwC Health Research Institute': ['research', 'strategy', 'healthcare'],
  'EY Health Sciences': ['consulting', 'strategy', 'healthcare'],
  'KPMG Healthcare': ['consulting', 'strategy', 'healthcare'],
  'Accenture Health': ['consulting', 'technology', 'digital health'],
  'Oliver Wyman Health': ['consulting', 'strategy', 'payer'],
  'Optum': ['consulting', 'data analytics', 'payer'],
  'Definitive Healthcare': ['data analytics', 'healthcare', 'research'],
  'Clarivate (formerly IBM Watson Health)': ['data analytics', 'technology', 'healthcare'],
  'Health Catalyst': ['data analytics', 'technology', 'healthcare'],
  'Truven Health Analytics': ['data analytics', 'research', 'healthcare'],
  'Lumeris': ['consulting', 'value-based care', 'technology'],

  // Search Firms / Staffing
  'WittKieffer': ['executive search', 'C-suite', 'healthcare'],
  'Korn Ferry Healthcare': ['executive search', 'C-suite', 'leadership'],
  'Spencer Stuart Healthcare': ['executive search', 'C-suite', 'health system'],
  'Heidrick & Struggles Healthcare': ['executive search', 'C-suite', 'leadership'],
  'Russell Reynolds Healthcare': ['executive search', 'C-suite', 'leadership'],
  'Tyler & Company': ['executive search', 'C-suite', 'healthcare'],
  'B.E. Smith': ['executive search', 'C-suite', 'healthcare'],
  'Merritt Hawkins': ['staffing', 'physician', 'healthcare'],
  'AMN Healthcare': ['staffing', 'nursing', 'healthcare'],
  'Cross Country Healthcare': ['staffing', 'nursing', 'healthcare'],
  'CHG Healthcare': ['staffing', 'physician', 'healthcare'],
  'CompHealth': ['staffing', 'physician', 'healthcare'],
  'Weatherby Healthcare': ['staffing', 'physician', 'healthcare'],
  'Aya Healthcare': ['staffing', 'nursing', 'healthcare'],
  'Medical Solutions': ['staffing', 'nursing', 'healthcare'],
  'LocumTenens.com': ['staffing', 'physician', 'healthcare'],
  'Furst Group': ['executive search', 'C-suite', 'healthcare'],
  'Buffkin Baker': ['executive search', 'C-suite', 'leadership'],

  // Women's Health / Resources
  'ACOG Resources': ['research', 'clinical', 'physician'],
  'March of Dimes': ['association', 'clinical', 'healthcare'],
  'National Women\'s Health Network': ['association', 'policy', 'healthcare'],
  'Office on Women\'s Health (HHS)': ['government', 'policy', 'healthcare'],
  'Society for Maternal-Fetal Medicine': ['association', 'clinical', 'physician'],
  'Women in Healthcare Leadership': ['association', 'leadership', 'C-suite'],
  'Catalyst (Women in Business)': ['research', 'leadership', 'healthcare'],

  // Provider / Physician Resources
  'AMA (American Medical Association)': ['association', 'physician', 'policy'],
  'Doximity': ['directory', 'physician', 'healthcare'],
  'Medscape': ['news', 'physician', 'clinical'],
  'UpToDate': ['research', 'physician', 'clinical'],
  'Physician Leadership Journal': ['journal', 'physician', 'leadership'],
  'NEJM (New England Journal of Medicine)': ['journal', 'physician', 'clinical'],
  'JAMA (Journal of the American Medical Association)': ['journal', 'physician', 'clinical'],
  'The Lancet': ['journal', 'physician', 'clinical'],
  'Annals of Internal Medicine': ['journal', 'physician', 'clinical'],
  'BMJ (British Medical Journal)': ['journal', 'physician', 'clinical'],
  'KevinMD': ['news', 'physician', 'leadership'],
  'Physician Practice': ['news', 'physician', 'ambulatory'],
  'Medical Economics': ['news', 'physician', 'healthcare'],
  'Physician Weekly': ['news', 'physician', 'clinical'],
  'The DO (Osteopathic Medicine)': ['news', 'physician', 'clinical'],
  'Texas Medical Association': ['association', 'physician', 'policy'],
  'MGMA Stat': ['research', 'physician', 'ambulatory'],
  'Physicians Foundation': ['research', 'physician', 'policy'],

  // Podcasts
  'The Becker\'s Podcast': ['podcast', 'C-suite', 'healthcare'],
  'Healthcare NOW Radio': ['podcast', 'technology', 'healthcare'],
  'Outcomes Rocket': ['podcast', 'innovation', 'healthcare'],
  'The Health Podcast Network': ['podcast', 'healthcare', 'clinical'],
  'HIT Like a Girl Podcast': ['podcast', 'technology', 'leadership'],
  'Flashpoint Health': ['podcast', 'innovation', 'healthcare'],
  'Day Zero Podcast': ['podcast', 'strategy', 'healthcare'],
  'Relentless Health Value': ['podcast', 'value-based care', 'healthcare'],
  'Healthcare Happy Hour': ['podcast', 'healthcare', 'leadership'],
  'In the Know Healthcare Podcast': ['podcast', 'supply chain', 'healthcare'],
  'HFMA\'s Voices in Healthcare Finance': ['podcast', 'revenue cycle', 'CFO'],
  'Oliver Wyman Health Podcast': ['podcast', 'strategy', 'healthcare'],
  'Hospitalogy Podcast': ['podcast', 'strategy', 'health system'],
  'The Gist Healthcare Podcast': ['podcast', 'healthcare', 'strategy'],
  'ACHE Healthcare Executive Podcast': ['podcast', 'leadership', 'C-suite'],
  'RevCycleIntelligence': ['podcast', 'revenue cycle', 'healthcare'],
  'Rural Health Podcast': ['podcast', 'rural health', 'healthcare'],

  // Consulting / Capital
  'Advisory Board': ['consulting', 'strategy', 'health system'],
  'Alvarez & Marsal Healthcare': ['consulting', 'strategy', 'healthcare'],
  'Cain Brothers': ['consulting', 'strategy', 'CFO'],
  'FTI Consulting Healthcare': ['consulting', 'strategy', 'healthcare'],
  'Juniper Advisory': ['consulting', 'strategy', 'healthcare'],
  'Kaufman Hall': ['consulting', 'CFO', 'strategy'],
  'Leerink Partners': ['consulting', 'strategy', 'healthcare'],
  'Piper Sandler Healthcare': ['consulting', 'strategy', 'CFO'],
  'Warbird Consulting Partners': ['consulting', 'strategy', 'healthcare'],
  'Ziegler Healthcare': ['consulting', 'strategy', 'CFO'],

  // National Accounts / Sales Support
  'Definitive Healthcare (Sales Intelligence)': ['data analytics', 'healthcare', 'tools'],
  'Becker\'s Hospital Review ASC': ['directory', 'ambulatory', 'healthcare'],
  'Lippincott NursingCenter': ['directory', 'nursing', 'healthcare'],
  'Healthcare Blue Book': ['tools', 'healthcare', 'data analytics'],
  'Sg2 Market Analytics': ['data analytics', 'strategy', 'health system'],
  'IQVIA': ['data analytics', 'pharmacy', 'research'],
  'Vizient Market Intelligence': ['data analytics', 'supply chain', 'GPO'],

  // Tools / Apps
  'Trello': ['tools', 'healthcare', 'strategy'],
  'Notion': ['tools', 'healthcare', 'strategy'],
  'Slack': ['tools', 'healthcare', 'technology'],
  'Zoom': ['tools', 'telehealth', 'technology'],
  'Microsoft Teams': ['tools', 'healthcare', 'technology'],
  'Canva': ['tools', 'healthcare', 'strategy'],
  'Grammarly': ['tools', 'healthcare', 'strategy'],
  'LinkedIn Sales Navigator': ['tools', 'healthcare', 'data analytics'],
  'Calendly': ['tools', 'healthcare', 'strategy'],
  'Loom': ['tools', 'healthcare', 'technology'],
  'ChatGPT': ['tools', 'AI', 'technology'],
  'Claude (Anthropic)': ['tools', 'AI', 'technology'],
  'Otter.ai': ['tools', 'AI', 'technology'],
  'Beautiful.ai': ['tools', 'healthcare', 'strategy'],
  'Figma': ['tools', 'technology', 'healthcare'],
  'Miro': ['tools', 'healthcare', 'strategy'],

  // Top News Sites
  'CNN Health': ['news', 'healthcare', 'policy'],
  'NPR Health': ['news', 'healthcare', 'policy'],
  'New York Times Health': ['news', 'healthcare', 'policy'],
  'Washington Post Health': ['news', 'healthcare', 'policy'],
  'Wall Street Journal Health': ['news', 'healthcare', 'CFO'],
  'Forbes Healthcare': ['news', 'healthcare', 'C-suite'],
  'Bloomberg Health': ['news', 'healthcare', 'strategy'],
  'Reuters Health': ['news', 'healthcare', 'clinical'],
  'AP Health': ['news', 'healthcare', 'policy'],
  'USA Today Health': ['news', 'healthcare', 'policy'],
  'The Hill Healthcare': ['news', 'policy', 'healthcare'],
  'Politico Health': ['news', 'policy', 'healthcare'],
  'Axios Health': ['news', 'healthcare', 'strategy'],
  'Vox Health': ['news', 'healthcare', 'policy'],
  'The Atlantic Health': ['news', 'healthcare', 'policy'],
  'Time Health': ['news', 'healthcare', 'policy'],

  // Travel Sites
  'Kayak': ['tools', 'healthcare', 'travel'],
  'Expedia': ['tools', 'healthcare', 'travel'],
  'Google Flights': ['tools', 'healthcare', 'travel'],
  'Hopper': ['tools', 'healthcare', 'travel'],
  'TripAdvisor': ['tools', 'healthcare', 'travel'],
  'Airbnb': ['tools', 'healthcare', 'travel'],
  'Hotels.com': ['tools', 'healthcare', 'travel'],
  'Southwest Airlines': ['tools', 'healthcare', 'travel'],

  // Time / Weather
  'World Clock': ['tools', 'healthcare', 'travel'],
  'Weather.com': ['tools', 'healthcare', 'travel'],
  'AccuWeather': ['tools', 'healthcare', 'travel'],
  'TimeAndDate.com': ['tools', 'healthcare', 'travel'],
  'World Time Buddy': ['tools', 'healthcare', 'travel'],
  'NOAA Weather': ['tools', 'healthcare', 'travel'],
  'Weather Underground': ['tools', 'healthcare', 'travel'],
  'Dark Sky (Apple Weather)': ['tools', 'healthcare', 'travel'],
};

async function run() {
  // Sign in as admin to bypass RLS
  const { error: authErr } = await supabase.auth.signInWithPassword({
    email: 'hays@ihesllc.com',
    password: process.env.SUPABASE_ADMIN_PASSWORD,
  });

  if (authErr) {
    console.error('Auth failed:', authErr.message);
    console.log('Set SUPABASE_ADMIN_PASSWORD env var and retry');

    // Try without auth (if RLS allows)
    console.log('\nTrying without auth...');
  }

  let updated = 0;
  let failed = 0;

  for (const [name, tags] of Object.entries(tagMap)) {
    const { error } = await supabase
      .from('resources')
      .update({ tags })
      .eq('name', name);

    if (error) {
      console.error(`FAILED: ${name} — ${error.message}`);
      failed++;
    } else {
      updated++;
    }
  }

  console.log(`\nDone: ${updated} updated, ${failed} failed out of ${Object.keys(tagMap).length} resources`);
}

run();
